<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customer Service</name>
   <tag></tag>
   <elementGuidId>85a9d328-6352-48e3-adb0-1a517e9a2ab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(24) > a.hmenu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[24]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>672e461f-1a40-4df1-9654-a8327feb6c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_em_cs_hm_0_1_1_38</value>
      <webElementGuid>50885ed2-8561-4609-8a6c-21f0a0452db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>fe7abd4e-1ede-48e2-ac8f-f7dd2dfa040b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Service</value>
      <webElementGuid>ceb273cd-58e6-4cbc-8932-12fb5703e2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible&quot;]/li[24]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>fab0d657-aebb-47ce-a91e-b0883cd9b713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[24]/a</value>
      <webElementGuid>9a4636db-870f-4bfe-be6c-dea9a5c73133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Customer Service')])[2]</value>
      <webElementGuid>5055b18c-f055-48d8-bdb6-732b25878c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_em_cs_hm_0_1_1_38')]</value>
      <webElementGuid>eda31719-eef6-43d2-9b62-b14483beb733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[24]/a</value>
      <webElementGuid>33408f0c-84d5-4ddb-815d-c9b83770bbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_em_cs_hm_0_1_1_38' and (text() = 'Customer Service' or . = 'Customer Service')]</value>
      <webElementGuid>567d0573-c8fa-4432-8e26-b60a599d6f23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
